GET http://localhost:3000/movies

###

GET http://localhost:3000/movies/642f2cb51aa509c540c3b0b1

###

POST http://localhost:3000/movies
Content-Type: application/json

{
    "name": "Superbad",
    "genre": "Comedy",
    "releaseDate": "5/15/2007"
}

###
PATCH http://localhost:3000/movies/642f33b5be0f084d94bd5afe
Content-Type: application/json

{
    "name": "No Country For Old Men"
}


###

DELETE http://localhost:3000/movies/642f20ffc2686e67f2dfd006